name: Deploy with Secret Credentials

on:
  push:
    branches: [main]  # Runs on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Uses a clean Ubuntu Linux environment

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Replace placeholders with secrets
     - name: Inject credentials
  run: |
    # Escape special characters in replacements
    sed -i "s|PLACEHOLDER_USERNAME|$(echo '${{ secrets.DASHBOARD_USERNAME }}' | sed 's/[\/&]/\\&/g')|g" index.html
    sed -i "s|PLACEHOLDER_PASSWORD|$(echo '${{ secrets.DASHBOARD_PASSWORD }}' | sed 's/[\/&]/\\&/g')|g" index.html
    sed -i "s|FIREBASE_API_KEY_PLACEHOLDER|$(echo '${{ secrets.FIREBASE_API_KEY }}' | sed 's/[\/&]/\\&/g')|g" *.html
    sed -i "s|FIREBASE_DATABASE_URL_PLACEHOLDER|$(echo '${{ secrets.FIREBASE_DATABASE_URL }}' | sed 's/[\/&]/\\&/g')|g" *.html

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Deploys all files in the root directory
