name: Deploy with Secret Credentials

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install envsubst
        run: sudo apt-get install -y gettext

      - name: Replace credentials in all HTML files
        run: |
          for file in *.html; do
            echo "Processing $file..."
            envsubst < "$file" > "$file.tmp" && mv "$file.tmp" "$file"
            # Verify replacements
            echo "=== Login Credentials ==="
            grep -A 2 "defaultUsername" "$file" || true
            echo "=== Firebase Config ==="
            grep -A 3 "firebaseConfig" "$file" || true
          done
        env:
          DASHBOARD_USERNAME: ${{ secrets.DASHBOARD_USERNAME }}
          DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}

      - name: Verify replacements
        run: |
          echo "=== Final Verification ==="
          grep -A 2 "defaultUsername" index.html
          grep -A 3 "firebaseConfig" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
