name: Deploy with Secret Credentials

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install replace-in-file
        run: npm install -g replace-in-file

      - name: Inject credentials
        run: |
          replace-in-file 'PLACEHOLDER_USERNAME' '${{ secrets.DASHBOARD_USERNAME }}' index.html
          replace-in-file 'PLACEHOLDER_PASSWORD' '${{ secrets.DASHBOARD_PASSWORD }}' index.html
          replace-in-file 'FIREBASE_API_KEY_PLACEHOLDER' '${{ secrets.FIREBASE_API_KEY }}' *.html
          replace-in-file 'FIREBASE_DATABASE_URL_PLACEHOLDER' '${{ secrets.FIREBASE_DATABASE_URL }}' *.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
