name: Deploy with Secret Credentials

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Replace credentials
        run: |
          # Replace login credentials
          sed -i "s/GHDEPLOY_DASHBOARD_USERNAME/${{ secrets.DASHBOARD_USERNAME }}/g" index.html
          sed -i "s/GHDEPLOY_DASHBOARD_PASSWORD/${{ secrets.DASHBOARD_PASSWORD }}/g" index.html
          
          # Replace Firebase config in all HTML files
          for file in *.html; do
            sed -i "s/FIREBASE_API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/g" "$file"
            sed -i "s/FIREBASE_DATABASE_URL_PLACEHOLDER/${{ secrets.FIREBASE_DATABASE_URL }}/g" "$file"
          done
          
          # Verify changes
          echo "=== Verification ==="
          grep "defaultUsername" index.html
          grep "defaultPassword" index.html

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
