name: Deploy with Secret Credentials

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace placeholders
        run: |
          # First install required tool
          sudo apt-get install -y gettext
          
          # For login credentials
          envsubst '${DASHBOARD_USERNAME}${DASHBOARD_PASSWORD}' < index.html > index.tmp
          mv index.tmp index.html
          
          # For Firebase config (all HTML files)
          for file in *.html; do
            envsubst '${FIREBASE_API_KEY}${FIREBASE_DATABASE_URL}' < "$file" > "$file.tmp"
            mv "$file.tmp" "$file"
          done
        env:
          DASHBOARD_USERNAME: ${{ secrets.DASHBOARD_USERNAME }}
          DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
