name: Deploy with Secret Credentials

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Replace credentials safely
        run: |
          # Escape special characters in secrets
          ESCAPED_USERNAME=$(printf '%s\n' "${{ secrets.DASHBOARD_USERNAME }}" | sed -e 's/[\/&]/\\&/g')
          ESCAPED_PASSWORD=$(printf '%s\n' "${{ secrets.DASHBOARD_PASSWORD }}" | sed -e 's/[\/&]/\\&/g')
          
          # Perform replacements
          sed -i "s/GH_USERNAME_PLACEHOLDER/${ESCAPED_USERNAME}/g" index.html
          sed -i "s/GH_PASSWORD_PLACEHOLDER/${ESCAPED_PASSWORD}/g" index.html
          
          # Verify changes
          echo "=== Credential Verification ==="
          grep -A 2 "defaultUsername" index.html || echo "No username found"
          grep -A 2 "defaultPassword" index.html || echo "No password found"

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
